### ISSUE TITLE
XSS Vulnerability

### ISSUE THREAD

**Issue by AntonUden** [manlaig/LiveChess#1]
if you type `<script>alert("hello");</script>` in the chat it runs the script. this could be used to make the game unplayable, to cheat or to hack users. Here is an example `<script>document.write("hacked");</script>` this would break the game.

you could add this script to the server to fix it `message = message.replace("<", "&lt;").replace(">", "&gt;");` remember to do this with the username too.

i can help you to fix it if you want 😃

**Comment by AntonUden** [comment]
i think your chatt-app [https://github.com/manlaig/chat-app](url) also has this Vulnerability in both the username and the chat messages

**Comment by manlaig** [comment]
Thank you for commenting Zeeraa, I have noticed the error also, but I thought it would be fun if I leave it as it is :)
